services:
  backend:
    build:
      context: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - my_network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - my_network

  test:
    build:
      context: .

    depends_on:
      - backend
      - redis
    networks:
      - my_network

volumes:
  redis_data:

networks:
  my_network:
