name: backend-deploy

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: backend:latest

      - name: Tag image with commit SHA
        id: meta
        run: |
          IMAGE_TAG=backend-${{ github.sha }}
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker tag backend:latest ${{ secrets.ECR_URL }}:$IMAGE_TAG


  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push image to ECR
        run: docker push ${{ secrets.ECR_URL }}:${{ needs.build.outputs.image_tag }}


  deploy:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-central-1

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ecs/task-def.json
          service: backend-service
          cluster: backend-cluster
          image: ${{ secrets.ECR_URL }}:${{ needs.build.outputs.image_tag }}
