name: backend-test

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts
          chmod 777 artifacts

      - uses: actions/checkout@v4

      - name: Build backend image
        run: docker compose -f docker-compose.yml build


  workload-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts
          chmod 777 artifacts

      - name: Build images
        run: docker compose -f docker-compose.yml build

      - name: Start stack
        run: docker compose -f docker-compose.yml up -d

      - name: Run endpoint workload tests
        run: docker compose -f docker-compose.yml run --rm test pytest tests/test_workload.py

      - name: Upload workload plot
        uses: actions/upload-artifact@v4
        with:
          name: workload-plot
          path: artifacts/workload_plot.png

      - name: Tear down stack
        if: always()
        run: docker compose -f docker-compose.yml down




  concurrency-test:
    needs: workload-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts
          chmod 777 artifacts
          

      - name: Build images
        run: docker compose -f docker-compose.yml build

      - name: Start stack
        run: docker compose -f docker-compose.yml up -d

      - name: Run endpoint concurrency tests
        run: docker compose -f docker-compose.yml run --rm test pytest tests/test_concurrency.py

      - name: Upload concurrency plot
        uses: actions/upload-artifact@v4
        with:
          name: concurrency-plot
          path: artifacts/concurrency_plot.png

      - name: Tear down stack
        if: always()
        run: docker compose -f docker-compose.yml down



