name: backend-test

on:
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker compose -f docker-compose.yml build 

      - name: Start full stack
        run: docker compose -f docker-compose.yml up -d 


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start full stack
        run: docker compose -f docker-compose.yml up -d

      - name: Run API stability tests
        run: docker compose -f docker-compose.yml run --rm test

      - name: Tear down stack
        if: always()
        run: docker compose -f docker-compose.yml down

